version: 2

jobs:
  "deploy_beta":
    docker: &DOCKERIMAGE
      - image: jenkinsrise/cci-latest-node-with-gcloud:0.0.1
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: git clone git@github.com:Rise-Vision/private-keys.git
      - run: npm install
      - run:
          name: Deploy to beta (test Web Store account)
<<<<<<< HEAD
          command: npm run deploy
=======
          command: |
            npm run bump
            npm run deploy
>>>>>>> c30ddd8... Bump before deploy

workflows:
  version: 2
  deploy:
    jobs:
      - "deploy_beta":
          requires:
          filters:
            branches:
              only:
                - master
