version: 2

jobs:
  "deploy_beta":
    docker: *DOCKERIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: git clone git@github.com:Rise-Vision/private-keys.git
      - run: npm install
      - run:
          name: Deploy to beta (test Web Store account)
          command: npm run deploy

workflows:
  version: 2
  deploy:
    jobs:
      - "deploy_beta":
          requires:
          filters:
            branches:
              only:
                - master
