version: 2

jobs:
  "test":
    docker: &DOCKERIMAGE
      - image: jenkinsrise/cci-latest-node-with-gcloud:0.0.1
    steps:
      - checkout
      - run: npm install
      - run:
          name: Unit Testing
          command: |
            npm run test

  "deploy_beta":
    docker: *DOCKERIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: git clone git@github.com:Rise-Vision/private-keys.git
      - run: npm install
      - run:
          name: Set staging url for content
          command: npm run set-staging-content
          command: npm run set-staging-segment-key
      - run:
          name: Deploy to beta (test Web Store account)
          command: |
            npm run test
            npm run bump
            npm run deploy

  "deploy_prod":
    docker: *DOCKERIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: git clone git@github.com:Rise-Vision/private-keys.git
      - run: npm install
      - run:
          name: Deploy to production
          environment:
            NODE_ENV: prod
          command: |
            npm run test
            npm run bump
            npm run deploy

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - "test"
      - "deploy_beta":
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - "deploy_prod":
          requires:
            - test
          filters:
            tags:
              only:
                - production
            branches:
              ignore:
                - /.*/
